### ISSUE TITLE
import experimente

### ISSUE THREAD

**Issue by Waog** [Waog/ReverseRpg#9]
- [x] billig char (texturen, animationen) in blender erstellen und in unity importieren
- [x] billig level in blender erstellen und in unity importieren
- [x] in unity charakteranimationen automatisch wechseln
- [x] rausfinden wo man collider definiert und es tun
  - [x] unsichtbare collider-meshes in blender definieren
  - [x] #26 automatically add mesh colliders to these meshes in unity

**Comment by thundersphinx** [comment]
Level Design komplett in Blender inklusive Texturen
